### ISSUE TITLE
【中软国际】【OBS】【关于通过终端节点访问OBS服务限制】

### ISSUE THREAD

**Issue by onemoretk** [huaweicloudDocs/obs#3]
【问题页面】https://developer.huaweicloud.com/endpoint
【问题描述】在方案中本来计划通过OBS终端节点内网访问OBS服务，但是在验证方案的时候发现除了拉美节点以外的其他地区所有的OBS终端节点服务均已下线，在各个文档当中又没有重点说明，希望在VPCEP,OBS服务相关的配置文档中进行说明！

**Comment by MrGourd** [comment]
您好，感谢您的反馈。您提交的内容已交由华为云工程师进行分析和评估，评估完成后会及时将结果反馈给您，请您留意Github消息。谢谢！

**Comment by MrGourd** [comment]
经评估，您反馈的问题已被接纳，当前在VPCEP的文档中已有相关说明，我们将在OBS文档中补充，计划于7月10日前发布至华为云帮助中心，上线进展将在Github同步给您。
VPCEP相关文档链接：
https://support.huaweicloud.com/qs-vpcep/vpcep_02_0301.html
https://support.huaweicloud.com/usermanual-vpcep/vpcep_03_0300.html

**Comment by MrGourd** [comment]
您反馈的问题在华为云帮助中心已发布，详见https://support.huaweicloud.com/bestpractice-obs/obs_05_0160.html 和 https://support.huaweicloud.com/qs-vpcep/vpcep_02_0301.html 。感谢并期待您的再次反馈。
