### ISSUE TITLE
请求参数 Authorization 到底是个啥，http 怎样才能调的通

### ISSUE THREAD

**Issue by xiaoerlangya** [huaweicloudDocs/obs#4]

**Comment by xiaoerlangya** [comment]
![image](https://user-images.githubusercontent.com/54572643/190073925-dd1a4ab3-61ed-46cb-8f1e-c87ac505c6b9.png)

**Comment by YoungSamLiu** [comment]
什么是Authorization，请参考https://support.huaweicloud.com/api-obs/obs_04_0010.html
